version: '2'
services:
    web:
        build: .
        ports:
            - 5055:5055
            - 5005:5005
        volumes:
            - .:/app
        depends_on:
            - redis
        restart: always
    redis:
        image: redis
        restart: always
